# Generated by Django 5.0.6 on 2024-06-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_create_at_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productcomment',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='productcomment',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='delete_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
