# Generated by Django 5.0.6 on 2024-06-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_delete_at_category_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
