# Generated by Django 5.0.6 on 2024-06-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_thumnail_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcomment'),
        ),
    ]
