# Generated by Django 5.0.6 on 2024-06-12 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcomment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcomment'),
        ),
    ]
