# Generated by Django 4.2.11 on 2024-06-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productcomment_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='parent_id',
        ),
    ]
